project:
  type: website

website:
  title: "Ayush Kumar"
  description: "Portfolio of Ayush Kumar - Associate AI Engineer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume/Entire_Resume.pdf
        text: Resume
        target: _blank
    right:
      - icon: github
        href: "https://github.com/Harper2123"
      - icon: linkedin
        href: "https://www.linkedin.com/in/ayush-kumar-4234b8155/"
      - icon: envelope
        href: "mailto:akcoolkmr@gmail.com"

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true

execute:
  freeze: true

page-footer: |
  © 2025 Ayush Kumar. Built with [Quarto](https://quarto.org).
