project:
  type: website

website:
  title: "Ayush Kumar"
  description: "Portfolio of Ayush Kumar - Data Science Professional"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: "https://github.com/Harper2123"
      - icon: linkedin
        href: "https://www.linkedin.com/in/ayush-kumar-4234b8155/"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
