name: Quarto Publish

on:
  push:
    branches: [main]  # Builds whenever you push to main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.33

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Setup Python (optional but safe)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
